version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dmodb
      - SPRING_DATASOURCE_USERNAME=dmouser
      - SPRING_DATASOURCE_PASSWORD=dmopass

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dmodb
      - POSTGRES_USER=dmouser
      - POSTGRES_PASSWORD=dmopass
    volumes:
      - postgres_data:var/lib/postgresql/data
volumes:
  postgresql_data:
